

export const START_NEW_CHAMPION_ALLIANCE = 'START_NEW_CHAMPION_ALLIANCE';
export const SUCCES_NEW_CHAMPION_ALLIANCE = 'SUCCES_NEW_CHAMPION_ALLIANCE';
export const ERROR_NEW_CHAMPION_ALLIANCE = 'ERROR_NEW_CHAMPION_ALLIANCE';
export const DEFAULT_NEW_CHAMPION_ALLIANCE = 'DEFAULT_NEW_CHAMPION_ALLIANCE';